### ISSUE TITLE
locking the child processes

### ISSUE THREAD

**Issue by thebestclass** [WyriHaximus/reactphp-child-process-messenger#2]
I am using the example `time-format` for testing.

in `format.php` file when I start some class, the child processes no longer work, see my code:

    <?php
    
    require dirname(dirname(__DIR__)) . '/vendor/autoload.php';
    require dirname(dirname(__DIR__)) . '/myclass.php';
    
    use React\EventLoop\Factory;
    use React\Promise\Deferred;
    use WyriHaximus\React\ChildProcess\Messenger\Messages\Invoke;
    use WyriHaximus\React\ChildProcess\Messenger\Messages\Payload;
    use WyriHaximus\React\ChildProcess\Messenger\Recipient;
    
    $loop = Factory::create();
    
    $myClass = new MyCLASS();
    
    $recipient = \WyriHaximus\React\ChildProcess\Messenger\Factory::child($loop);
    $recipient->registerRpc('format', function (Payload $payload) use ($loop, $myClass) {
        $myClass->executeAction();
    
        return \React\Promise\resolve([
            'formattedTime' => (new DateTime('@' . $payload['unixTime']))->format('c'),
        ]);
    });
    
    $loop->run();

But if I remove `$myClass = new MyCLASS();` everything will work normally, which can be?

**Comment by WyriHaximus** [comment]
What is MyCLASS doing? Causing any errors some how?

**Comment by thebestclass** [comment]
Normal funcions, no, no have errors with the class.



I forgot how to put the error scope in format.php 😞
Em segunda-feira, 30 de novembro de 2015, Cees-Jan Kiewiet <
notifications@github.com> escreveu:

> What is MyCLASS doing? Causing any errors some how?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WyriHaximus/reactphp-child-process-messenger/issues/2#issuecomment-160748981>
> .
>


-- 
Atenciosamente,
*Vinícius Eduardo S. L*

CEO *Wobbly*

**Comment by WyriHaximus** [comment]
Take a look at: https://github.com/WyriHaximus/reactphp-child-process-messenger/blob/master/examples/time-format/time.php#L18-L20

**Comment by thebestclass** [comment]
How put erro scope in format.php?

**Comment by WyriHaximus** [comment]
Put it in `time.php`, also run `format.php` by hand to test if no parse errors or anything else comes up.
