### ISSUE TITLE
It requires a process to wait for the other to run?

### ISSUE THREAD

**Issue by thebestclass** [WyriHaximus/reactphp-child-process-messenger#3]
a process is necessary to wait for other processes to run?

Because, I created a Web Socket server, and for it to be completely asynchronous I did that way, I am doing right? He will have locks?`(the code is merely illustrative)`

  
    namespace MyApp;
    use Ratchet\MessageComponentInterface;
    use Ratchet\ConnectionInterface;
    
    class Chat implements MessageComponentInterface {
        public function onOpen(ConnectionInterface $conn) {
            $messenger->rpc(MessageFactory::rpc('open', [
                'data' => $conn->resourceId,
            ]))->then(function () {});
        }
    
        public function onMessage(ConnectionInterface $from, $msg) {
            $messenger->rpc(MessageFactory::rpc('message', [
                'data' => $msg,
            ]))->then(function () {});
        }
    
        public function onClose(ConnectionInterface $conn) {
            $messenger->rpc(MessageFactory::rpc('close', [
                'data' => $conn->resourceId,
            ]))->then(function () {});
        }
    
        public function onError(ConnectionInterface $conn, \Exception $e) {
            $messenger->rpc(MessageFactory::rpc('error', [
                'data' => $e,
            ]))->then(function () {});
        }
    }

**Comment by thebestclass** [comment]
@WyriHaximus  hey?

**Comment by WyriHaximus** [comment]
When spawning processes it doesn't wait for other processes the way a pool does. Are you planning to spawn a process for each on* method on your websocket service?

**Comment by thebestclass** [comment]
@WyriHaximus  So to say that this way the server is completely asynchronous?

**Comment by WyriHaximus** [comment]
That is going to spawn a process for each and every call to those methods. With a lot of messages/sec that is going to be just as many processes/sec you're spawning. You might want to consider using a pool if that is what you intend to do.

**Comment by thebestclass** [comment]
@WyriHaximus  My intention is to leave the fully asynchronous server, How would this method?

**Comment by WyriHaximus** [comment]
The pool method? Swap $messenger out with $pool and the rpcs work as if they where $messenger's.

**Comment by thebestclass** [comment]
@WyriHaximus What do you mean? but $pool is not defined. Could you show me? 

This method would be more correct and let the asynchronous server? I would face any complications?

**Comment by WyriHaximus** [comment]
Well neither is $messenger in your example, used it as example. Take a look at https://github.com/wyrihaximus/reactphp-child-process-pool/ 

Without knowing exactly what you're going to do I honestly can't answer if you would face any complications.

**Comment by thebestclass** [comment]
@WyriHaximus I have several functions that block, such as MySQL, RSA encrypt/decrypt etc .. and for me it is easier to place the child processes right at the server scope `(on*)` ..

**Comment by WyriHaximus** [comment]
Ah yeah thank you for explaining. But my recommendation would be to use a pool instead so you have a control over the number of processes spawned.

**Comment by thebestclass** [comment]
@WyriHaximus in both cases the asynchronicity is maintained? and what problem using the normal process that I showed up?

**Comment by WyriHaximus** [comment]
Yes both do that but with your example if you get 1000 calls at the same time you'll spawn 1000 processes at the same time unless you instantiate it as a property for that class your example doesn't include that.

**Comment by thebestclass** [comment]
@WyriHaximus and that's bad? How would I do to solve this problem?

**Comment by WyriHaximus** [comment]
Depending on your hardware spawning 1000 processes could be very bad.

Are you spawning a process per message or using a single process for the
entire service?

**Comment by thebestclass** [comment]
@WyriHaximus  I am using a single child process for the whole server...

**Comment by WyriHaximus** [comment]
That will work. But keep an eye on the backlog of calls if it gets to big
swap it out for a pool.

Personally I would use a flexible pool just for the mysql calls and a
flexible one for the encryption limited to the number of cpu cores.

**Comment by thebestclass** [comment]
@WyriHaximus great idea, I'm trying to do things the right way not to have a headache, I believe that reaching a flow of 1,000 per second would be a big headache.

You could better explain your idea?

**Comment by thebestclass** [comment]
@WyriHaximus I thought I'd do the following, create a child process for each call `(on*)` so as not to congest only one child process, this would solve effectively?

**Comment by thebestclass** [comment]
@WyriHaximus I thought I'd do the following, create a child process for each call `(on*)` so as not to congest only one child process, this would solve effectively?

**Comment by thebestclass** [comment]
another question, have a way to pass the $conn interface to the child
process? I tried with super closure and serialize and the normal mode but
anything worked

Em sábado, 26 de dezembro de 2015, Cees-Jan Kiewiet <
notifications@github.com> escreveu:

> That will work. But keep an eye on the backlog of calls if it gets to big
> swap it out for a pool.
>
> Personally I would use a flexible pool just for the mysql calls and a
> flexible one for the encryption limited to the number of cpu cores.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WyriHaximus/reactphp-child-process-messenger/issues/3#issuecomment-167369886>
> .
>


-- 
Atenciosamente,
*Vinícius Eduardo S. L*

CEO *Wobbly*

**Comment by WyriHaximus** [comment]
Don't create a child process per call, it can easily take down your server when there are a lot. Also just pass on the information you need from `$conn` rather then the whole object.

**Comment by thebestclass** [comment]
@WyriHaximus 

I ignored you warning and after the number of process 240 the server returns me these errors:

proc_open(): unable to create pipe Too many open files
Unable to launch a new process.

and take down...

You know how to fix?

**Comment by WyriHaximus** [comment]
Hey I warned you for a few reasons :wink: . You can solve this by raising the max open filedescriptor limits: http://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/

**Comment by thebestclass** [comment]
@WyriHaximus I'm sorry I ignored, it took me a few weeks to understand how this worked repository that at the end I needed to change again, it makes me upset.

Well, if I change what told me I will have the same performance as the pool? Or the pool is really better? 

Can you explain why it would be better for then we close this topic?

**Comment by thebestclass** [comment]
@WyriHaximus 

I'm sorry I ignored, it took me a few weeks to understand how this worked repository that at the end I needed to change again, it makes me upset.

Well, if I change what told me I will have the same performance as the pool? Or the pool is really better? 

Can you explain why it would be better for then we close this topic?

**Comment by WyriHaximus** [comment]
Just leave it open for now. I'm currently rewriting the pool package to be more modular and make sure everything works as it should. My suggestion is to use a pool as it can balance the work better and scale up or down as you might need. I'll let you know when the pool refactor is done.

**Comment by thebestclass** [comment]
@WyriHaximus Hey, how are u? How long...

Well, i have a problem and i need solve this, well, im still with the problem of the most processes. I would like fix it for ever because this is boring... So:

I'm finishing my big project, messaging server, and now I'm in the testing phase I own problems. When the second user connects the server does not support the processes and lock my MySQL not allowing new connections. I really want to solve this once, I went to your repository (reactphp-child-process-pool) but did not get success. Could you please help me?

ps: Amazingly, this happened after 13 processes. My MacBook its overloaded hardware ...

ps2: I thought a possible solution would not be possible to close each process after use? For it seems to me that when opening a process it is open infinitely.

**Comment by WyriHaximus** [comment]
If you run the MySQL connection run it in a flexible pool where the min size is set to 0 so it is only connected when you use it. Also don't open a connection per user, pool the connections among users instead.
