### ISSUE TITLE
Custom autoload.php not read in child process

### ISSUE THREAD

**Issue by FGIKCM** [WyriHaximus/reactphp-child-process-messenger#32]
In `child-process.php`, you check for autoload.php in specific folders. But if we use a custom `autoload.php` in our project, which is on another place, this one is not read, and obviously the child class can't be instancied.

It would be nice to have an option in `Flexible::createFromClass()` (or equivalent) to specify some files to `require` in the child-process.php

**Comment by WyriHaximus** [comment]
> In `child-process.php`, you check for autoload.php in specific folders. But if we use a custom `autoload.php` in our project, which is on another place, this one is not read, and obviously the child class can't be instancied.

Out of interest why do you have a custom `autoload.php`?
 
> It would be nice to have an option in `Flexible::createFromClass()` (or equivalent) to specify some files to `require` in the child-process.php

I'm open for a PR adding support for this.

**Comment by FGIKCM** [comment]
I have an `autoload.php` generated by Composer, and another one to handle my namespaces, which basically:
 - include the Composer autoload
 - do a `spl_autoload_register()` to manage my own classes

For the PR, OK. I will just wait to be sure my project would fit with your great project. For now I struggle with messages not sent to parent when the child terminate fast. (I will investigate my code before opening another issue :) )

**Comment by WyriHaximus** [comment]
> I have an `autoload.php` generated by Composer, and another one to handle my namespaces, which basically:
> 
> * include the Composer autoload
> * do a `spl_autoload_register()` to manage my own classes

Don't they follow PSR-0/PSR-4? Alternatively you can look into [`classmap`](https://getcomposer.org/doc/04-schema.md#classmap) or [`files`](https://getcomposer.org/doc/04-schema.md#files).

> For the PR, OK. I will just wait to be sure my project would fit with your great project. For now I struggle with messages not sent to parent when the child terminate fast. (I will investigate my code before opening another issue :) )

Sounds like the child is erroring out

**Comment by FGIKCM** [comment]
ooooh I didn't even knew I could do that in the composer.json! Thanks a lot!
Indeed, adding this in my composer.json did the trick. No need to alter your code anymore^^
```json
"autoload": {
		"psr-4": {
			"KCM\\Servers\\": "servers/"
		}
	},
```

For memo, to apply this change in Composer:
```batch
composer dump-autoload --no-dev -o -vvv
```
(Source : https://phpenthusiast.com/blog/how-to-autoload-with-composer)

So you can close this issue.

**Comment by WyriHaximus** [comment]
Happy to help :sunglasses: .

Another option would be to`composer update --lock` which will only update the lock file and dump the autoloader
