### ISSUE TITLE
Why ChildInterface->create() return type is void?

### ISSUE THREAD

**Issue by roipoussiere** [WyriHaximus/reactphp-child-process-messenger#66]
In [ChildInterface](https://github.com/WyriHaximus/reactphp-child-process-messenger/blob/master/src/ChildInterface.php#L11):

```php
interface ChildInterface
{
    public static function create(Messenger $messenger, LoopInterface $loop): void;
}
```

The `void` return type has been added in 9dc16b4bb0eb2d3ef90cc5b43b88e96d5078f6ac. Is it a new behavior and create must actually return nothing?

This breaks [this project](https://github.com/reactphp/filesystem), where in the implemented class, `create()` method [returns the object instance](https://github.com/reactphp/filesystem/blob/master/src/ChildProcess/Process.php#L20).

**Comment by WyriHaximus** [comment]
Not returning anything is the expected behaviour, which wasn't enforced in the past and is now causing an unexpected issue there. Looking into a fix for it. 

Refs: https://github.com/WyriHaximus/reactphp-child-process-pool/issues/69

**Comment by WyriHaximus** [comment]
Just did a few releases resolving this issue. Please reopen this issue if it somehow persists for you.
