### ISSUE TITLE
OS detector vs PHP_BINARY?

### ISSUE THREAD

**Issue by elazar** [WyriHaximus/reactphp-child-process-messenger#9]
`PHP_BINARY` is [available since 5.4](http://php.net/manual/en/reserved.constants.php), this library's [minimum version](https://github.com/WyriHaximus/reactphp-child-process-messenger/blob/05e9a8aee1c119cd622383bbd86a6509c8d7308e/composer.json#L13). Why not use that versus requiring an [additional dependency](https://github.com/WyriHaximus/reactphp-child-process-messenger/blob/05e9a8aee1c119cd622383bbd86a6509c8d7308e/composer.json#L18) for [OS detection](https://github.com/WyriHaximus/reactphp-child-process-messenger/blob/05e9a8aee1c119cd622383bbd86a6509c8d7308e/src/Factory.php#L159-L171)?

**Comment by WyriHaximus** [comment]
Hah awesome! Wasn't aware of `PHP_BINARY` that makes things a whole lot easier :+1: ! Would you like to file a PR or should I file it?

**Comment by elazar** [comment]
I can submit one. 😄 Just wanted to make sure there wasn't some reason I wasn't aware of for the current approach.

**Comment by WyriHaximus** [comment]
Nah just OS detection, but this would be a way better solution :+1:
