### ISSUE TITLE
Proposal - drop indigophp/hash-compat

### ISSUE THREAD

**Issue by FGIKCM** [WyriHaximus/reactphp-child-process-messenger#92]
Hello,

The [indigophp/hash-compat](https://github.com/indigophp/hash-compat) project has been abandoned.
It was made to add the `hash_*` functions to old PHP versions.

On each `composer update` we do, we now have a warning telling us we should avoid using it.

After reading the doc of `hash_equals`, I see that it was introduced in PHP 5.6: https://www.php.net/manual/en/function.hash-equals.php
The PHP end of life branches page states that PHP 5.5 was abandoned on 2016 and is no more supported:
https://www.php.net/eol.php

So I propose to not use the  indigophp/hash-compat project anymore, and just use the internal PHP versions.

**Comment by WyriHaximus** [comment]
Hey @FGIKCM if you want to create PR's for this to the `master` and `4.x` branches I'd be more than happy to remove this and create a new release.

**Comment by WyriHaximus** [comment]
Just tagged [`4.0.3`](https://github.com/WyriHaximus/reactphp-child-process-messenger/releases/tag/4.0.3) with this in it, and it will also be part of the 5.0.0 release sometime in the future.
